apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flowforge.fullname" . }}-config
  labels:
    {{- include "flowforge.labels" . | nindent 4 }}
data:
  FLOWFORGE_ENV: {{ .Values.env | quote }}
  FLOWFORGE_LOG_LEVEL: {{ .Values.logLevel | quote }}
  POSTGRES_HOST: {{ include "flowforge.postgresHost" . | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.port | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_SSL_MODE: {{ .Values.postgresql.sslMode | quote }}
  POSTGRES_MAX_CONNS: {{ .Values.postgresql.maxConnections | quote }}
  REDIS_HOST: {{ include "flowforge.redisHost" . | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIS_DB: {{ .Values.redis.db | quote }}
  TEMPORAL_HOST: {{ .Values.temporal.host | quote }}
  TEMPORAL_PORT: {{ .Values.temporal.port | quote }}
  TEMPORAL_NAMESPACE: {{ .Values.temporal.namespace | quote }}
  S3_ENDPOINT: {{ .Values.minio.endpoint | quote }}
  S3_BUCKET: {{ .Values.minio.bucket | quote }}
  S3_REGION: {{ .Values.minio.region | quote }}
  VAULT_ADDR: {{ .Values.vault.address | quote }}
