apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowforge.fullname" . }}-secret
  labels:
    {{- include "flowforge.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  S3_ACCESS_KEY: {{ .Values.minio.accessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.minio.secretKey | b64enc | quote }}
  VAULT_TOKEN: {{ .Values.vault.token | b64enc | quote }}
  FLOWFORGE_ENCRYPTION_KEY: {{ .Values.encryptionKey | b64enc | quote }}
